// Generated by scripts/generate-release-info.mjs. Do not edit.
export const APP_VERSION: string = "0.1.0";
export const APP_CHANGELOG: string = "# Changelog\n\nAll notable changes to PR-Orch are documented here. Releases follow\n[Semantic Versioning](https://semver.org/). Add a release with\n`npm run release -- <patch|minor|major|x.y.z> \"<summary>\"`.\n\n## [0.1.0] - 2026-10-02\n\nAdded application release versioning: the root `package.json` version is the\nsource of truth, shown in the dashboard with these release notes, and bumped\nwith `npm run release`.\n";
